MIN_CARACTERES = 2
MAX_CARACTERES = 8

DURACION_RONDA_INICIAL = 60
VELOCIDAD_AUTOS = 5
VELOCIDAD_TRONCOS = 5
PONDERADOR_DIFICULTAD = 0.6

VIDAS_INICIO = 3

VELOCIDAD_CAMINAR = 45
PIXELES_SALTO = 80

TIEMPO_AUTOS = 6000
TIEMPO_TRONCOS = 5000

TIEMPO_OBJETOS = 6

CANTIDAD_MONEDAS = 5